/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mevResistantDexSol from "./MEVResistantDEX.sol";
export type { mevResistantDexSol };
import type * as realDexIntegrationSol from "./RealDexIntegration.sol";
export type { realDexIntegrationSol };
export type { MEVDex } from "./MEVDex";
export type { MainnetConfig } from "./MainnetConfig";
export type { MockERC20 } from "./MockERC20";
export type { NetworkConfig } from "./NetworkConfig";
export type { OneInchIntegration } from "./OneInchIntegration";
export type { WorkingMultiDex } from "./WorkingMultiDex";
