/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface NetworkConfigInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "SEPOLIA_SUSHISWAP_ROUTER"
      | "SEPOLIA_UNISWAP_V2_ROUTER"
      | "SEPOLIA_UNISWAP_V3_ROUTER"
      | "SEPOLIA_WETH"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "SEPOLIA_SUSHISWAP_ROUTER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SEPOLIA_UNISWAP_V2_ROUTER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SEPOLIA_UNISWAP_V3_ROUTER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SEPOLIA_WETH",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "SEPOLIA_SUSHISWAP_ROUTER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SEPOLIA_UNISWAP_V2_ROUTER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SEPOLIA_UNISWAP_V3_ROUTER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SEPOLIA_WETH",
    data: BytesLike
  ): Result;
}

export interface NetworkConfig extends BaseContract {
  connect(runner?: ContractRunner | null): NetworkConfig;
  waitForDeployment(): Promise<this>;

  interface: NetworkConfigInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  SEPOLIA_SUSHISWAP_ROUTER: TypedContractMethod<[], [string], "view">;

  SEPOLIA_UNISWAP_V2_ROUTER: TypedContractMethod<[], [string], "view">;

  SEPOLIA_UNISWAP_V3_ROUTER: TypedContractMethod<[], [string], "view">;

  SEPOLIA_WETH: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "SEPOLIA_SUSHISWAP_ROUTER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SEPOLIA_UNISWAP_V2_ROUTER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SEPOLIA_UNISWAP_V3_ROUTER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SEPOLIA_WETH"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
