/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ISwapRouter } from "./ISwapRouter";
export type { IUniswapV2Router02 } from "./IUniswapV2Router02";
export type { IUniswapV3Quoter } from "./IUniswapV3Quoter";
export type { RealDexIntegration } from "./RealDexIntegration";
