/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  MainnetConfig,
  MainnetConfigInterface,
} from "../../contracts/MainnetConfig";

const _abi = [
  {
    inputs: [],
    name: "MAINNET_DEPLOYMENT",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MAINNET_UNISWAP_V2_ROUTER",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MAINNET_UNISWAP_V3_ROUTER",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MAINNET_WETH",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "SEPOLIA_UNISWAP_V2_ROUTER",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "SEPOLIA_UNISWAP_V3_ROUTER",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "SEPOLIA_WETH",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getUniswapV2Router",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "getUniswapV3Router",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "getWethAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "isMainnet",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506101d1806100206000396000f3fe608060405234801561001057600080fd5b50600436106100a85760003560e01c80637ff975ff116100715780637ff975ff1461014357806382e57465146100e0578063a87773f41461015e578063b235af0e14610166578063b9e3de4414610181578063f927e767146100fb57600080fd5b806271c175146100ad57806305bf0c40146100e05780630a9f47a3146100fb57806323a7b42a1461011657806342faac0514610130575b600080fd5b737a250d5630b4cf539739df2c5dacb4c659f2488d5b6040516001600160a01b0390911681526020015b60405180910390f35b6100c373e592427a0aece92de3edee1f18e0157c0586156481565b6100c3737a250d5630b4cf539739df2c5dacb4c659f2488d81565b737b79995e5f793a07bc00c21412e50ecae098e7f96100c3565b60005b60405190151581526020016100d7565b6100c373c02aaa39b223fe8d0a0e5c4f27ead9083c756cc281565b610133600081565b6100c3737b79995e5f793a07bc00c21412e50ecae098e7f981565b73e592427a0aece92de3edee1f18e0157c058615646100c356fea26469706673582212202dfc6acc309e132d48526cfd3f27282ad3b60d37a81004707229f9a2b324202e64736f6c63430008140033";

type MainnetConfigConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MainnetConfigConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MainnetConfig__factory extends ContractFactory {
  constructor(...args: MainnetConfigConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MainnetConfig & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MainnetConfig__factory {
    return super.connect(runner) as MainnetConfig__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MainnetConfigInterface {
    return new Interface(_abi) as MainnetConfigInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MainnetConfig {
    return new Contract(address, _abi, runner) as unknown as MainnetConfig;
  }
}
